### ISSUE TITLE
[PublicMarket] PHP Fatal error:  Uncaught Error: Access to undeclared static property

### ISSUE THREAD

**Issue by paladine007** [jhaagsma/ee_npc#1]
I saw you updated the PublicMarket.class, was this the error that you fixed?

[18:52:00] Try to buy goods at 230 dpnw or below to reach DPA of 49 from 13!PHP Fatal error:  Uncaught Error: Access to undeclared static property: EENPC\PublicMarket::$changed in /usr/local/www/ee_npc/PublicMarket.class.php:31
Stack trace:
#0 /usr/local/www/ee_npc/country_functions.php(346): EENPC\PublicMarket::update()
#1 /usr/local/www/ee_npc/country_functions.php(392): EENPC\minDpnw(Object(EENPC\Country), true)
#2 /usr/local/www/ee_npc/Country.class.php(414): EENPC\defend_self(Object(EENPC\Country), 23838090)
#3 /usr/local/www/ee_npc/techer_strat.php(260): EENPC\Country->countryGoals(Array, 1450416)
#4 /usr/local/www/ee_npc/techer_strat.php(77): EENPC\buy_techer_goals(Object(EENPC\Country), 1450416)
#5 /usr/local/www/ee_npc/ee_npc.php(209): EENPC\play_techer_strat(Object(stdClass), 79)
#6 {main}
  thrown in /usr/local/www/ee_npc/PublicMarket.class.php on line 31

**Comment by jhaagsma** [comment]
I was kindof generally refactoring, and breaking a lot of things; unfortunately a lot of the behaviours that were breaking weren't showing up in the AI Server (less market dynamics), so I actually had to commit & push & pull to Alliance to test them

But no, I didn't fix that; just looking now; I *can* fix that though!

**Comment by jhaagsma** [comment]
Should be fixed now!

**Comment by paladine007** [comment]
Great! Did another pull and we'll see if anything else comes up :)

**Comment by jhaagsma** [comment]
Exellent! I'll close for now then!
