### ISSUE TITLE
Unexpected Result for 'create': ERROR:MAXIMUM_COUNTRIES_REACHED

### ISSUE THREAD

**Issue by paladine007** [jhaagsma/ee_npc#2]
Not sure what is going on here lol. Infinite loop, repeating through what is happening below. Maybe the server hasn't started yet? But I would expect it to sleep rather than trying to create countries repeatedly...

[00:13:29] Less countries than allowed! (0/25)
[00:13:29] Making new country named 'Frozen Parachute'
[00:13:29] 

Unexpected Result for 'create': ERROR:MAXIMUM_COUNTRIES_REACHED

[00:13:29] Server Output: 
{"ERROR":"MAXIMUM_COUNTRIES_REACHED"}
[00:13:29] Frozen Parachute (#MAXIMUM_COUNTRIES_REACHED) created!
[00:13:29] Less countries than allowed! (0/25)
[00:13:29] Making new country named 'Basilisk Sunny'
[00:13:29] 

Unexpected Result for 'create': ERROR:MAXIMUM_COUNTRIES_REACHED

[00:13:29] Server Output: 
{"ERROR":"MAXIMUM_COUNTRIES_REACHED"}
[00:13:29] Basilisk Sunny (#MAXIMUM_COUNTRIES_REACHED) created!
[00:13:29] Less countries than allowed! (0/25)
[00:13:29] Making new country named 'Mylene'
[00:13:29]

**Comment by paladine007** [comment]
Seems to be working now, so maybe it is limited to the time between the set ending and a new one starting?

**Comment by jhaagsma** [comment]
It seems to not have updated that it *HAS* countries?

Hm.

I wonder if it's due to cached bits expiring at different times.

I think this may actually be more of a game issue than a bot issue, but we should probably still handle weird server outputs on the bot side lol....

**Comment by paladine007** [comment]
Yeah it looks like it could be server side, though I don't think it was an issue with updating that it has countries created. After stopping the bot and starting again it went through the expected process where the 25 new countries were created.

On the AI server, are you allowed to create counties before the set has officially started? ee_npc.php checks the alive_count first and tries to create countries, then checks if the server has started.

**Comment by jhaagsma** [comment]
You should be able to, I would think...

**Comment by jhaagsma** [comment]
I just pushed a change that should fix this....

**Comment by paladine007** [comment]
Nice!
