### ISSUE TITLE
PHP Recoverable fatal error: communication.php line 146

### ISSUE THREAD

**Issue by paladine007** [jhaagsma/ee_npc#4]
It looks like the latest update to communication.php broke something...

[15:15:19] Allies for def full!PHP Recoverable fatal error:  Object of class stdClass could not be converted to string in /usr/local/www/ee_npc/communication.php on line 146

**Comment by paladine007** [comment]
Something in the $response var on this line:
out("\n\nUnexpected Result for '$function': ".$message.':'.$response."\n\n");

var_dump of $response:
object(stdClass)#57 (1) {
  ["results"]=>
  NULL
}

**Comment by paladine007** [comment]
Found the issue and created a pull request

**Comment by paladine007** [comment]
Actually the issue if the out function not liking the object is still a problem... 

I just found the earlier issue where the code was failing an elseif that lead to this specific out() call lol

**Comment by jhaagsma** [comment]
I think this one is done?
